[package]
name = "produp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
csv = "1.2.2"
epaint= "0.22.0"
serde = { version = "1.0.183", features = ["derive"] }
